import jinja2

EXERCISE_TEMPLATE_STR = """\
<div
    data-type="injected-exercise"
    class="{{ data.class }}"
    data-injected-from-nickname="{{ data.metadata.nickname }}"
    data-injected-from-url="{{ data.url }}"
    data-tags="{{ ' '.join(data.metadata.tags) }}">
    {% if data.required_context -%}
    <div data-type="exercise-context"
        data-context-module="{{ data.required_context.module }}"
        data-context-feature="{{ data.required_context.feature }}">
        <a class="autogenerated-content"
        href="#{{ data.required_context.ref }}">[link]</a>
    </div>
    {% endif -%}
    {% if data.metadata.stimulus -%}
    <div data-type="exercise-stimulus">{{ data.metadata.stimulus }}</div>
    {% endif -%}
    {% for question in data.questions -%}
    <div
        data-type="exercise-question"
        data-is-answer-order-important="{{ question.is_answer_order_important | lower }}"
        data-formats="{{ ' '.join(question.formats) }}"
        {% if question.id %}data-id="{{ question.id }}"{% endif %}
        >
        {% if question.stimulus -%}
        <div data-type="question-stimulus">{{ question.stimulus }}</div>
        {% endif -%}
        <div data-type="question-stem">{{ question.html }}</div>
        {% if question.answers -%}
        <ol data-type="question-answers" type="a">
            {% for option in question.answers -%}
            <li data-type="question-answer" data-id="{{ option.id }}" data-correctness="{{ option.correctness }}">
                <div data-type="answer-content">{{ option.html }}</div>
                {% if option.feedback %}<div data-type="answer-feedback">{{ option.feedback }}</div>{% endif %}
            </li>
            {% endfor -%}
        </ol>
        {% endif -%}
        {% for solution in question.collaborator_solutions -%}
        <div data-type="question-solution" data-solution-source="collaborator" data-solution-type="{{ solution.type }}">
            {{ solution.html }}
        </div>
        {% endfor -%}
    </div>
    {% endfor -%}
</div>
"""

EXERCISE_TEMPLATE = jinja2.Template(EXERCISE_TEMPLATE_STR)
