#!/usr/bin/env bash

set -eo pipefail

fetch() {
    if ! curl -sSL "$1"; then
        echo "Failed to download $1" >&2
        return 1
    fi
}

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="gitleaks/gitleaks"
DEFAULT_BRANCH="$(fetch "https://api.github.com/repos/$REPO" | jq -r '.default_branch')"
GITLEAKS="https://github.com/$REPO/raw/refs/heads/$DEFAULT_BRANCH/config/gitleaks.toml"
LICENSE="https://github.com/$REPO/raw/refs/heads/$DEFAULT_BRANCH/LICENSE"

{
    fetch "$LICENSE" | awk '$0="# "$0'
    echo
    echo
    fetch "$GITLEAKS" | \
    tomlq '[
        .rules[] |
        select(
            (.id | contains("slack")) or
            (.id | contains("github")) or
            (.id | contains("aws-")) or
            (.id | contains("jwt")) or
            (.id == "generic-api-key") or
            (.id == "private-key")
        ) |
        { id: .id, regex: .regex }
    ]' | jq -r '
    "# This file is automatically generated. Do not edit it manually.\n" +
    "\n" +
    "patterns = " + (. | tostring)
    '
} | \
black - > "$HERE/scripts/secret_patterns.py"
